# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mensagem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mensagem.proto',
  package='',
  serialized_pb=_b('\n\x0emensagem.proto\"X\n\x08Mensagem\x12\x0c\n\x04tipo\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0e\n\x06objeto\x18\x03 \x02(\t\x12\x0e\n\x06metodo\x18\x04 \x02(\t\x12\x12\n\nargumentos\x18\x05 \x03(\x0c\x42\tB\x07Message')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MENSAGEM = _descriptor.Descriptor(
  name='Mensagem',
  full_name='Mensagem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tipo', full_name='Mensagem.tipo', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Mensagem.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='objeto', full_name='Mensagem.objeto', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metodo', full_name='Mensagem.metodo', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='argumentos', full_name='Mensagem.argumentos', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Mensagem'] = _MENSAGEM

Mensagem = _reflection.GeneratedProtocolMessageType('Mensagem', (_message.Message,), dict(
  DESCRIPTOR = _MENSAGEM,
  __module__ = 'mensagem_pb2'
  # @@protoc_insertion_point(class_scope:Mensagem)
  ))
_sym_db.RegisterMessage(Mensagem)


DESCRIPTOR.has_options = True
# @@protoc_insertion_point(module_scope)
