# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rotas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rotas.proto',
  package='',
  serialized_pb=_b('\n\x0brotas.proto\"<\n\x05Passo\x12\x11\n\tinstrucao\x18\x01 \x02(\t\x12\x11\n\tdistancia\x18\x02 \x02(\t\x12\r\n\x05tempo\x18\x03 \x02(\t\"o\n\x04Rota\x12\x0e\n\x06idRota\x18\x01 \x02(\x05\x12\x16\n\x0e\x65nderecoOrigem\x18\x02 \x02(\t\x12\x17\n\x0f\x65nderecoDestino\x18\x03 \x02(\t\x12\x0f\n\x07tamanho\x18\x04 \x02(\t\x12\x15\n\x05passo\x18\x05 \x03(\x0b\x32\x06.Passo\" \n\tListaRota\x12\x13\n\x04rota\x18\x01 \x03(\x0b\x32\x05.Rota')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PASSO = _descriptor.Descriptor(
  name='Passo',
  full_name='Passo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrucao', full_name='Passo.instrucao', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distancia', full_name='Passo.distancia', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tempo', full_name='Passo.tempo', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=75,
)


_ROTA = _descriptor.Descriptor(
  name='Rota',
  full_name='Rota',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idRota', full_name='Rota.idRota', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enderecoOrigem', full_name='Rota.enderecoOrigem', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enderecoDestino', full_name='Rota.enderecoDestino', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tamanho', full_name='Rota.tamanho', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passo', full_name='Rota.passo', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=188,
)


_LISTAROTA = _descriptor.Descriptor(
  name='ListaRota',
  full_name='ListaRota',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rota', full_name='ListaRota.rota', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=222,
)

_ROTA.fields_by_name['passo'].message_type = _PASSO
_LISTAROTA.fields_by_name['rota'].message_type = _ROTA
DESCRIPTOR.message_types_by_name['Passo'] = _PASSO
DESCRIPTOR.message_types_by_name['Rota'] = _ROTA
DESCRIPTOR.message_types_by_name['ListaRota'] = _LISTAROTA

Passo = _reflection.GeneratedProtocolMessageType('Passo', (_message.Message,), dict(
  DESCRIPTOR = _PASSO,
  __module__ = 'rotas_pb2'
  # @@protoc_insertion_point(class_scope:Passo)
  ))
_sym_db.RegisterMessage(Passo)

Rota = _reflection.GeneratedProtocolMessageType('Rota', (_message.Message,), dict(
  DESCRIPTOR = _ROTA,
  __module__ = 'rotas_pb2'
  # @@protoc_insertion_point(class_scope:Rota)
  ))
_sym_db.RegisterMessage(Rota)

ListaRota = _reflection.GeneratedProtocolMessageType('ListaRota', (_message.Message,), dict(
  DESCRIPTOR = _LISTAROTA,
  __module__ = 'rotas_pb2'
  # @@protoc_insertion_point(class_scope:ListaRota)
  ))
_sym_db.RegisterMessage(ListaRota)


# @@protoc_insertion_point(module_scope)
